Add SonarQube quality gate check and report upload

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -57,6 +57,26 @@ jobs:
             -Dsonar.sources=. \
             -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} \
             -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
+
+      - name: SonarQube Quality Gate
+        run: |
+          sleep 15
+          STATUS=$(curl -s -u ${{ secrets.SONARQUBE_TOKEN }}: \
+          "${{ secrets.SONARQUBE_HOST }}/api/qualitygates/project_status?projectKey=simple-python-app" \
+          | jq -r '.projectStatus.status')
+
+          echo "Quality Gate Status: $STATUS"
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality Gate Failed"
+            exit 1
+          fi
+
+      - name: Upload Sonar Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: sonarqube-report
+          path: .scannerwork/
+          
   update-env:
       name: update secrets
       runs-on: manish-ec2
@@ -65,5 +85,3 @@ jobs:
         - name: update .env file 
           run: |
             python3 update-secrets.py
-        
-
